// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Muonroi.Microservices.Data.Persistence;

#nullable disable

namespace Muonroi.Microservices.Data.Persistence.Migrations
{
    [DbContext(typeof(BaseTemplateDbContext))]
    [Migration("20260126155851_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MLanguage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<double>("CreatedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(16);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(20);

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(21);

                    b.Property<double?>("DeletedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(18);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(25);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(24);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Icon")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(19);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(22);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(17);

                    b.Property<Guid?>("LastModificationUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(23);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_MLanguages_Name");

                    b.ToTable("MLanguages");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<double>("CreatedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(24);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(28);

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(29);

                    b.Property<double?>("DeletedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(26);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(33);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(32);

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Icon")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(27);

                    b.Property<bool>("IsGranted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(30);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(25);

                    b.Property<Guid?>("LastModificationUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(31);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<int?>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(10);

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<string>("ParentUiKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<Guid?>("PermissionGroupId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(13);

                    b.Property<long?>("PermissionGroupId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasMaxLength(32)
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<string>("UiKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_MPermissions_Name");

                    b.HasIndex("ParentId");

                    b.HasIndex("PermissionGroupId1");

                    b.HasIndex("PermissionGroupId", "UiKey")
                        .IsUnique()
                        .HasDatabaseName("IX_MPermissions_Group_UiKey");

                    b.ToTable("MPermissions");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MPermissionAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<double>("CreatedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(16);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(20);

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(21);

                    b.Property<double?>("DeletedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(18);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(25);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(24);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(19);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(22);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(17);

                    b.Property<Guid?>("LastModificationUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(23);

                    b.Property<Guid?>("PerformedBy")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_MPermissionAuditLogs_RoleId");

                    b.ToTable("MPermissionAuditLogs");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MPermissionGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<double>("CreatedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(14);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(18);

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(19);

                    b.Property<double?>("DeletedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(16);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(23);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(22);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(17);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(20);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(15);

                    b.Property<Guid?>("LastModificationUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(21);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_MPermissionGroups_Name");

                    b.ToTable("MPermissionGroups");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MRefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<double>("CreatedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(19);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(23);

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(24);

                    b.Property<double?>("DeletedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(21);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(28);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(27);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ExpiredDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(22);

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(25);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(20);

                    b.Property<Guid?>("LastModificationUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(26);

                    b.Property<DateTime>("LastUsedDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<string>("ReasonRevoked")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("RevokedDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("TokenValidityKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("MRefreshTokens");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<double>("CreatedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(18);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(22);

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(23);

                    b.Property<double?>("DeletedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(20);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(27);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(26);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(21);

                    b.Property<bool>("IsStatic")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(24);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(19);

                    b.Property<Guid?>("LastModificationUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(25);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_MRoles_Name");

                    b.ToTable("MRoles");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MRolePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<double>("CreatedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(14);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(18);

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(19);

                    b.Property<double?>("DeletedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(16);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(23);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(22);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(17);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(20);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(15);

                    b.Property<Guid?>("LastModificationUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(21);

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("MRolePermissions");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(16);

                    b.Property<double>("CreatedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(34);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(38);

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(39);

                    b.Property<double?>("DeletedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(36);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(43);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(42);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("ExternalLoginProvider")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(22);

                    b.Property<string>("ExternalLoginToken")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(23);

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(13);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(37);

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(12);

                    b.Property<bool>("IsPhoneNumberConfirmed")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(9);

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(11);

                    b.Property<bool>("IsUseThirdPartyLogin")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(21);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(40);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(35);

                    b.Property<Guid?>("LastModificationUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(41);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<string>("NormalizedEmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(15);

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(14);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<int?>("ProfilePictureId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(18);

                    b.Property<string>("Salt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(17);

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(10);

                    b.Property<bool>("ShouldChangePasswordOnNextLogin")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(19);

                    b.Property<DateTime?>("SignInTokenExpireTimeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(20);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_MUser_UserName");

                    b.ToTable("MUsers");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MUserLoginAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("AttemptTime")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(8);

                    b.Property<string>("BrowserInfo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<string>("ClientIpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<double>("CreatedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(20);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(24);

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(25);

                    b.Property<double?>("DeletedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(22);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(29);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(28);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(23);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(26);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(21);

                    b.Property<Guid?>("LastModificationUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(27);

                    b.Property<DateTime>("LockTo")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<byte>("Result")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(7);

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("UserNameOrEmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("UserNameOrEmailAddress")
                        .HasDatabaseName("IX_MUserLoginAttempt_UserNameOrEmailAddress");

                    b.ToTable("MUserLoginAttempts");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<double>("CreatedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(14);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(18);

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(19);

                    b.Property<double?>("DeletedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(16);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(23);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(22);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(17);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(20);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(15);

                    b.Property<Guid?>("LastModificationUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(21);

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("MUserRoles");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MUserToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<double>("CreatedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(17);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(21);

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(22);

                    b.Property<double?>("DeletedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(19);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(26);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(25);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(20);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(23);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(18);

                    b.Property<Guid?>("LastModificationUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(24);

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("LoginProvider")
                        .HasDatabaseName("IX_MUserToken_LoginProvider");

                    b.ToTable("MUserTokens");
                });

            modelBuilder.Entity("Muonroi.Microservices.Core.Domain.NotificationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<double>("CreatedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(19);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(23);

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(24);

                    b.Property<double?>("DeletedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(21);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(28);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(27);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(22);

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(25);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(20);

                    b.Property<Guid?>("LastModificationUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(26);

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Muonroi.Microservices.Core.Domain.SampleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<double>("CreatedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(13);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(17);

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(18);

                    b.Property<double?>("DeletedDateTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(15);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(22);

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(21);

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(16);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(19);

                    b.Property<double?>("LastModificationTimeTs")
                        .HasColumnType("REAL")
                        .HasColumnOrder(14);

                    b.Property<Guid?>("LastModificationUserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(20);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MPermission", b =>
                {
                    b.HasOne("Muonroi.BuildingBlock.External.Entity.Identity.MPermission", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasPrincipalKey("EntityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Muonroi.BuildingBlock.External.Entity.Identity.MPermissionGroup", "PermissionGroup")
                        .WithMany()
                        .HasForeignKey("PermissionGroupId1");

                    b.Navigation("Parent");

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("Muonroi.BuildingBlock.External.Entity.Identity.MPermission", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
